/******************************
脚本名称：蛋蛋不语VIP解锁
Version  : v1.0.0
更新时间：2026-05-31
作者：Curtinp118
Platform : Quantumult X
脚本功能：解锁蛋蛋不语VIP会员功能
使用说明：添加到重写，打开蛋蛋不语App即可生效
*******************************/

# 蛋蛋不语
DOMAIN-SUFFIX,one.one.one.one,DIRECT
DOMAIN-SUFFIX,api.wwzy.tv,DIRECT
DOMAIN-SUFFIX,bfzyapi.com,DIRECT
DOMAIN-SUFFIX,img.picbf.com,DIRECT
DOMAIN-SUFFIX,v10.baofeng10.com,DIRECT
DOMAIN-SUFFIX,icanhazip.com,DIRECT
DOMAIN-SUFFIX,captive.apple.com,DIRECT
DOMAIN-SUFFIX,ajax.googleapis.com,DIRECT
DOMAIN-SUFFIX,s1.fengbao9.com,DIRECT
DOMAIN-SUFFIX,develop202.github.io,DIRECT
DOMAIN-SUFFIX,s2.bfllvip.com,DIRECT
IP-CIDR,38.76.202.248/32,DIRECT

[rewrite_local]
^http:\/\/38\.76\.202\.248:8000\/.*profiles.* url script-response-body https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/dandanvip/dandanvip_unlock.js

[MITM]
hostname = 38.76.202.248
