/******************************
脚本名称：DreamFace解锁
Version  : v1.0.0
更新时间：2026-05-31
作者：Curtinp118
Platform : Quantumult X
脚本功能：解锁DreamFace会员功能
使用说明：添加到重写，打开DreamFace App即可生效
*******************************/

[rewrite_local]
https://www.dreamfaceapp.com/df-server/user/save_user_login url script-response-body https://raw.githubusercontent.com/curtinp118/Scripthub/main/scripts/dreamface/dreamface.js

[MITM]
hostname = www.dreamfaceapp.com
